# SpringBoot configuration
server:
  port: 8081
  shutdown: graceful

# DB configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        check_nullability: true


  datasource:
    url: jdbc:mysql://localhost:3306/BudgetApp
    username: SpringBootDBUser
    password: SpringBootPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

# Logging
logging:
#  file:
#    name: src/main/resources/logs/crud.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
#    crud: DEBUG
    com.budgetApp: DEBUG


