CREATE TABLE CATEGORIES (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	PARENT_CATEGORY INT,
	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID),
	CONSTRAINT UC_CATEGORIES_NAME UNIQUE(NAME),
	CONSTRAINT FK_CATEGORIES_PARENTCATEGORY FOREIGN KEY (PARENT_CATEGORY) REFERENCES CATEGORIES(ID)
);
