CREATE TABLE CATEGORIES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	PARENT_CATEGORY_ID BIGINT,
	TYPE VARCHAR(1) NOT NULL,
	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID),
	CONSTRAINT UC_CATEGORIES_NAME UNIQUE(NAME),
	CONSTRAINT FK_CATEGORIES_PARENT_CATEGORY FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE MONTHS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    YEAR UNSIGNED SMALLINT NOT NULL,
    MONTH UNSIGNED TINYINT NOT NULL,
    NOTES VARCHAR(255),
    CONSTRAINT PK_MONTHS PRIMARY KEY (ID),
    CONSTRAINT UC_MONTHS_YEAR_MONTH UNIQUE(YEAR, MONTH)
);

CREATE TABLE MONTHLY_BUDGETS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MONTH_ID BIGINT NOT NULL,
	CATEGORY_ID BIGINT NOT NULL,
	INITIAL_BALANCE DECIMAL(8,2) NOT NULL DEFAULT 0,
	AMOUNT DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT 0,
	CONSTRAINT PK_MONTHLY_BUDGETS PRIMARY KEY(ID),
	CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE INCOMES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(50) NOT NULL,
    PAYER VARCHAR(50),
    MONTH_ID BIGINT NOT NULL,
    AMOUNT DECIMAL(8,2) UNSIGNED NOT NULL,
    DATE DATE NOT NULL,
    CONSTRAINT PK_INCOMES PRIMARY KEY(ID),
    CONSTRAINT FK_INCOMES_MONTH FOREIGN KEY (MONTH_ID) REFERENCES MONTHS(ID)
);

CREATE TABLE SPENDINGS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MONTHLY_BUDGET_ID BIGINT NOT NULL,
	AMOUNT DECIMAL(8,2) UNSIGNED NOT NULL,
	PAYEE VARCHAR(50) NOT NULL,
	DATE DATE NOT NULL,
	CONSTRAINT SPENDINGS_PK PRIMARY KEY(ID),
	CONSTRAINT FK_SPENDINGS_MONTHLY_BUDGET FOREIGN KEY (MONTHLY_BUDGET_ID) REFERENCES MONTHLY_BUDGETS(ID)
);
