CREATE TABLE MONTHLYBUDGET (
	ID INT NOT NULL AUTO_INCREMENT,
	BUDGET_ID INT NOT NULL,
	MONTH INT NOT NULL,
	YEAR INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	INITIAL_BALANCE INT NOT NULL DEFAULT 0,
	AMOUNT INT NOT NULL DEFAULT 0,
	CONSTRAINT PK_MONTHLYBUDGET PRIMARY KEY(ID),
	CONSTRAINT FK_BUDGET FOREIGN KEY (BUDGET_ID) REFERENCES BUDGETS(ID),
	CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);
