CREATE TABLE SPENDINGS (
	ID INT NOT NULL AUTO_INCREMENT,
	MONTHLYBUDGET_ID INT NOT NULL,
	AMOUNT INT NOT NULL,
	PAYEE VARCHAR(50) NOT NULL,
	SPENDING_DATE DATE NOT NULL,
	CONSTRAINT SPENDING_PK PRIMARY KEY(ID),
	CONSTRAINT FK_SPENDING_MONTHLYBUDGET FOREIGN KEY (MONTHLYBUDGET_ID) REFERENCES MONTHLYBUDGET(ID)
);
